### PR TITLE
adding --untar option to decrypto

### PR DESCRIPTION
**Pull request by chrisidefix**
I am not 100% confident about the extraction in sub-directories. I tested it and it works the way it is now, but maybe we should run some proper test scenarios for this one.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
merging this weekend.  thanks for all of your efforts on this!

**Comment by chrisidefix** [comment]
no worries - I enjoy using it, too!

**Comment by chrissimpkins** [comment]
Apologize for the delay in getting to this.  Tests are nearly complete for the `--tar` flag and will start on this.  I think we should eliminate the optional approach and make this the default for any tar archives that are encountered following decryption.

**Comment by chrisidefix** [comment]
Generally, I agree that it should be the default to untar, but I would then suggest to add an explicit option to allow users not to untar files after decryption (e.g. --no-untar)?

**Comment by chrissimpkins** [comment]
merged with a new `--nountar` flag using default untar for decrypted tar archives and the optional flag to remove this default.  

have some work to do on the directory structure of the unpacked files when they are not unpacked into the working directory and for the way that directories packed inside of tar archives are handled.  starting work on that in development branch.

**Comment by chrissimpkins** [comment]
seems to be working.  you can pull the current development branch to give it a try.  will be adding tests.

**Comment by chrisidefix** [comment]
Great, I'll have a look at it soon.

**Comment by chrissimpkins** [comment]
I really like this.  It's a great addition.

**Comment by chrissimpkins** [comment]
do you have an account that you would prefer me to link on the contributors list?  Twitter? Your github account?  If you are willing to share your name I would like to acknowledge your efforts when I announce this release.

**Comment by chrisidefix** [comment]
Thanks Chris, I'll send you an e-mail to the address linked on your profile.

**Comment by chrissimpkins** [comment]
Sounds great

**Comment by chrissimpkins** [comment]
got your email. thanks much.  

tests are all passing and I think we are ready to push this release.  will finish docs tomorrow and push to pypi. 

let me know if you have any thoughts or additional suggestions.

**Comment by chrisidefix** [comment]
Yes, looks good to me from what I have seen. I guess what is left is the documentation. `settings.py` and `README.md` should probably include the new options. I would also suggest to add a comment in there somewhere that the extracted archive is being delete after untar completed.

**Comment by chrissimpkins** [comment]
sounds good.  hope to push later today.

**Comment by chrissimpkins** [comment]
Released on PyPI.  Thanks for all of your efforts on this release.  It looks great.

**Pull request merged**
